[package]
name = "dashi-server"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.39.2", features = ["full"] }
#axum
axum = {version = "0.7.5", features = ["macros"] }
tower-http = { version = "0.5.2", features = ["cors"] }
#DDD
application ={ path = "./src/application" }
domain = { path = "./src/domain" }
#seaorm
sea-orm = { version = "1.0.0", features = [ "sqlx-postgres", "runtime-tokio-native-tls", "macros" ] }
migration = { path = "migration" }
entity = { path = "entity" }
