[package]
name = "dashi-server"
version = "0.1.0"
edition = "2024"

[dependencies]
#DDD
application ={ path = "./src/application" }
domain = { path = "./src/domain" }
#seaorm
sea-orm = { version = "1.0.0", features = [ "sqlx-postgres", "runtime-tokio-native-tls", "macros" ] }
migration = { path = "migration" }
entity = { path = "entity" }
