[package]
name = "init"
version.workspace = true
edition.workspace = true

[dependencies]
# DDD
domain = { path = "../domain" }
# dependencies
tokio.workspace = true
## axum
axum.workspace = true
tower-http.workspace = true
