[package]
name = "application"
version.workspace = true
edition.workspace = true

[dependencies]
#DDD
domain = { path = "../domain" }
# axum
async-std.workspace = true
serde.workspace = true
utoipa.workspace = true
# seaorm
entity.workspace = true
