[package]
name = "presentation"
version.workspace = true
edition.workspace = true

[dependencies]
# DDD
application ={ path = "../application" }
domain = { path = "../domain" }
# dependencies
tokio.workspace = true
## axum
axum.workspace = true
tower-http.workspace = true
